name: Continuous Integration (CI)

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Check Git status
        run: git status  
      - name: Clean Git repository
        run: git reset --hard && git clean -fd

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Check Node.js version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

